from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label} count={count}")
    return text.replace(old, new, 1)


def replace_audio_score_calls(text: str) -> str:
    marker = "scoreYoutubeAudioTrackPreference(format) +"
    count = text.count(marker)
    if count != 2:
        raise SystemExit(f"direct audio scoring site count={count}")
    for _ in range(2):
        start = text.index(marker)
        call_start = text.index("scoreAudioFormat(", start)
        depth = 0
        call_end = None
        for index in range(call_start, len(text)):
            char = text[index]
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    call_end = index + 1
                    break
        if call_end is None:
            raise SystemExit("unterminated scoreAudioFormat call")
        call = text[call_start:call_end]
        replacement = f"strictAudioSelectionScore(youtubeAudioTrackTier(format), {call})"
        text = text[:start] + replacement + text[call_end:]
    return text


resolver = Path("app/src/main/java/com/luc4n3x/levyra/data/PlaybackResolver.kt")
text = resolver.read_text(encoding="utf-8")
old = '''internal fun scoreYoutubeAudioTrackPreference(format: JSONObject): Int {
    val audioTrack = format.optJSONObject("audioTrack") ?: return 0
    return when {
        audioTrack.optBoolean("isAutoDubbed", false) -> -1_000_000
        audioTrack.optBoolean("audioIsDefault", false) -> 250_000
        else -> 0
    }
}
'''
new = '''private const val AUDIO_TRACK_SCORE_BAND = 10_000_000
private const val AUDIO_FORMAT_SCORE_LIMIT = AUDIO_TRACK_SCORE_BAND / 2 - 1

internal fun youtubeAudioTrackTier(format: JSONObject): Int {
    val audioTrack = format.optJSONObject("audioTrack") ?: return 1
    return when {
        audioTrack.optBoolean("isAutoDubbed", false) -> 0
        audioTrack.optBoolean("audioIsDefault", false) -> 2
        else -> 1
    }
}

internal fun extractorAudioTrackTier(type: AudioTrackType?, autoGenerated: Boolean): Int = when {
    autoGenerated -> 0
    type == AudioTrackType.ORIGINAL -> 5
    type == null -> 4
    type == AudioTrackType.SECONDARY -> 3
    type == AudioTrackType.DUBBED -> 2
    type == AudioTrackType.DESCRIPTIVE -> 1
    else -> 1
}

internal fun strictAudioSelectionScore(trackTier: Int, formatScore: Int): Int =
    trackTier * AUDIO_TRACK_SCORE_BAND +
        formatScore.coerceIn(-AUDIO_FORMAT_SCORE_LIMIT, AUDIO_FORMAT_SCORE_LIMIT)
'''
text = replace_once(text, old, new, "audio preference helper")
text = replace_audio_score_calls(text)
old = '''        val trackBonus = when (stream.audioTrackType) {
            AudioTrackType.ORIGINAL -> 1_000_000
            AudioTrackType.DUBBED -> -200_000
            AudioTrackType.DESCRIPTIVE -> -300_000
            AudioTrackType.SECONDARY -> -100_000
            null -> 0
        }
        val generatedPenalty = if (stream.itagItem?.isAutoGenerated == true) -250_000 else 0
        return trackBonus + generatedPenalty +
            scoreAudioFormat(mime, stream.formatId, stream.averageBitrate, "", preferMp4Audio, audioQuality)
'''
new = '''        val trackTier = extractorAudioTrackTier(
            stream.audioTrackType,
            stream.itagItem?.isAutoGenerated == true
        )
        return strictAudioSelectionScore(
            trackTier,
            scoreAudioFormat(mime, stream.formatId, stream.averageBitrate, "", preferMp4Audio, audioQuality)
        )
'''
text = replace_once(text, old, new, "extractor score block")
resolver.write_text(text, encoding="utf-8")

app_test = Path("app/src/test/java/com/luc4n3x/levyra/data/YoutubeExtractorFallbackContractTest.kt")
text = app_test.read_text(encoding="utf-8")
if "import org.schabi.newpipe.extractor.stream.AudioTrackType\n" not in text:
    text = text.replace(
        "import org.json.JSONObject\n",
        "import org.json.JSONObject\nimport org.schabi.newpipe.extractor.stream.AudioTrackType\n",
        1,
    )
start = text.index("    @Test\n    fun directAudioSelectionStronglyPenalizesAutoDubbedTracks()")
end = text.index("    @Test\n    fun youtubeJsonReadAcceptsSmallPayloads()", start)
replacement = "\n".join([
    "    @Test",
    "    fun directAudioSelectionUsesNonOverlappingTrackTiers() {",
    "        val autoDubbed = JSONObject().put(",
    "            \"audioTrack\",",
    "            JSONObject().put(\"isAutoDubbed\", true).put(\"audioIsDefault\", true)",
    "        )",
    "        val originalDefault = JSONObject().put(",
    "            \"audioTrack\",",
    "            JSONObject().put(\"isAutoDubbed\", false).put(\"audioIsDefault\", true)",
    "        )",
    "",
    "        assertEquals(0, youtubeAudioTrackTier(autoDubbed))",
    "        assertEquals(2, youtubeAudioTrackTier(originalDefault))",
    "        assertEquals(1, youtubeAudioTrackTier(JSONObject()))",
    "        assertTrue(",
    "            strictAudioSelectionScore(youtubeAudioTrackTier(originalDefault), -4_999_999) >",
    "                strictAudioSelectionScore(youtubeAudioTrackTier(autoDubbed), 4_999_999)",
    "        )",
    "    }",
    "",
    "    @Test",
    "    fun extractorTrackTierKeepsOriginalAndHumanAudioAboveAutoGeneratedAudio() {",
    "        assertTrue(",
    "            extractorAudioTrackTier(AudioTrackType.ORIGINAL, false) >",
    "                extractorAudioTrackTier(AudioTrackType.DUBBED, false)",
    "        )",
    "        assertTrue(",
    "            extractorAudioTrackTier(AudioTrackType.DUBBED, false) >",
    "                extractorAudioTrackTier(AudioTrackType.DUBBED, true)",
    "        )",
    "    }",
    "",
    "",
])
app_test.write_text(text[:start] + replacement + text[end:], encoding="utf-8")

canary = Path("scripts/youtube_canary.py")
text = canary.read_text(encoding="utf-8")
text = replace_once(text, "SCHEMA_VERSION = 1", "SCHEMA_VERSION = 2", "schema version")
old = '    accepted = baseline.get("observation")\n    if not isinstance(accepted, dict):\n'
new = "\n".join([
    '    accepted = baseline.get("observation")',
    '    baseline_schema = baseline.get("schema")',
    '    if baseline_schema is None and isinstance(accepted, dict):',
    '        baseline_schema = accepted.get("schema")',
    '    if isinstance(accepted, dict) and baseline_schema != SCHEMA_VERSION:',
    '        return {',
    '            "decision": "blocked",',
    '            "severity": "warning",',
    '            "material_changes": [],',
    '            "informational_changes": [',
    '                f"Accepted baseline schema {baseline_schema!r} is incompatible with current schema "',
    '                f"{SCHEMA_VERSION}; accept a fresh observation before comparison."',
    '            ],',
    '        }',
    '    if not isinstance(accepted, dict):',
    '',
])
canary.write_text(replace_once(text, old, new, "baseline classify marker"), encoding="utf-8")

canary_test = Path("scripts/tests/test_youtube_canary.py")
text = canary_test.read_text(encoding="utf-8")
text = replace_once(
    text,
    'self.assertEqual(1, baseline["schema"])',
    'self.assertEqual(canary.SCHEMA_VERSION, baseline["schema"])',
    "baseline schema assertion",
)
old = '            "schema": 1,\n            "sentinels": ['
text = replace_once(
    text,
    old,
    '            "schema": canary.SCHEMA_VERSION,\n            "sentinels": [',
    "observation schema helper",
)
anchor = "    def test_required_sentinels_expect_adaptive_video(self):\n"
extra = "\n".join([
    "    def test_legacy_baseline_is_blocked_before_format_comparison(self):",
    '        legacy = self._observation(js="a", ok=True, formats=8, adaptive_video=5, muxed_video=1)',
    '        legacy["schema"] = 1',
    '        legacy["sentinels"][0]["observation"]["player"].pop("adaptive_video_formats", None)',
    '        legacy["sentinels"][0]["observation"]["player"].pop("muxed_video_formats", None)',
    '        after = self._observation(js="b", ok=True, formats=2, adaptive_video=0, muxed_video=1)',
    "",
    "        decision = canary._classify(",
    '            {"schema": 1, "observation": legacy},',
    "            after,",
    '            {"thresholds": {"required_sentinel_regressions_for_repair": 1}},',
    "        )",
    "",
    '        self.assertEqual("blocked", decision["decision"])',
    '        self.assertTrue(any("baseline schema" in item.lower() for item in decision["informational_changes"]))',
    "",
    "",
])
canary_test.write_text(replace_once(text, anchor, extra + anchor, "canary test anchor"), encoding="utf-8")

helper = Path("third_party/LevyraExtractor/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java")
text = helper.read_text(encoding="utf-8")
start = text.index("    @Nullable\n    public static String extractXtagsValue(@Nullable final String xtags,")
end = text.index("\n    private static long readProtoVarint", start)
replacement = "\n".join([
    "    @Nullable",
    "    public static String extractXtagsValue(@Nullable final String xtags,",
    "                                           @Nonnull final String wantedKey) {",
    "        if (isNullOrEmpty(xtags)) {",
    "            return null;",
    "        }",
    "        final String protobufValue = extractProtobufXtagsValue(xtags, wantedKey);",
    "        if (!isNullOrEmpty(protobufValue)) {",
    "            return protobufValue;",
    "        }",
    '        for (final String pair : xtags.split(":")) {',
    "            final int separator = pair.indexOf('=');",
    "            if (separator <= 0) {",
    "                continue;",
    "            }",
    "            if (wantedKey.equals(pair.substring(0, separator))) {",
    "                return pair.substring(separator + 1);",
    "            }",
    "        }",
    "        return null;",
    "    }",
    "",
    "    @Nullable",
    "    private static String extractProtobufXtagsValue(@Nonnull final String xtags,",
    "                                                          @Nonnull final String wantedKey) {",
    "        try {",
    '            final String padded = xtags + "====".substring(0, (4 - xtags.length() % 4) % 4);',
    "            final byte[] data = Base64.getUrlDecoder().decode(padded);",
    "            int position = 0;",
    "            while (position < data.length) {",
    "                final int[] cursor = {position};",
    "                final long tag = readProtoVarint(data, cursor);",
    "                position = cursor[0];",
    "                if ((tag & 7) != 2) {",
    "                    return null;",
    "                }",
    "                final long pairLength = readProtoVarint(data, cursor);",
    "                position = cursor[0];",
    "                if (pairLength < 0 || pairLength > data.length - position) {",
    "                    return null;",
    "                }",
    "                final int pairEnd = position + (int) pairLength;",
    "                String key = null;",
    "                String value = null;",
    "                while (position < pairEnd) {",
    "                    cursor[0] = position;",
    "                    final long pairTag = readProtoVarint(data, cursor);",
    "                    position = cursor[0];",
    "                    if ((pairTag & 7) != 2) {",
    "                        return null;",
    "                    }",
    "                    final long length = readProtoVarint(data, cursor);",
    "                    position = cursor[0];",
    "                    if (length < 0 || length > pairEnd - position) {",
    "                        return null;",
    "                    }",
    "                    final String fieldValue = new String(data, position, (int) length,",
    "                            StandardCharsets.UTF_8);",
    "                    position += (int) length;",
    "                    final int field = (int) (pairTag >>> 3);",
    "                    if (field == 1) {",
    "                        key = fieldValue;",
    "                    } else if (field == 2) {",
    "                        value = fieldValue;",
    "                    }",
    "                }",
    "                if (wantedKey.equals(key)) {",
    "                    return value;",
    "                }",
    "                position = pairEnd;",
    "            }",
    "        } catch (final IllegalArgumentException ignored) {",
    "        }",
    "        return null;",
    "    }",
    "",
])
helper.write_text(text[:start] + replacement + text[end:], encoding="utf-8")

extractor_test = Path("third_party/LevyraExtractor/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeModernAudioMetadataTest.java")
text = extractor_test.read_text(encoding="utf-8")
anchor = "    @Test\n    void copyConstructorPreservesModernFormatMetadataAndIdentity() throws Exception {\n"
extra = "\n".join([
    "    @Test",
    "    void parsesColonDelimitedXtagsAfterProtobufFallback() {",
    '        final String xtags = "acont=original:lang=en-US:label=Studio=Master";',
    "",
    "        assertEquals(AudioTrackType.ORIGINAL, YoutubeParsingHelper.extractAudioTrackType(xtags));",
    '        assertEquals("en-US", YoutubeParsingHelper.extractXtagsValue(xtags, "lang"));',
    '        assertEquals("Studio=Master", YoutubeParsingHelper.extractXtagsValue(xtags, "label"));',
    '        assertNull(YoutubeParsingHelper.extractXtagsValue(xtags, "missing"));',
    "    }",
    "",
    "",
])
extractor_test.write_text(replace_once(text, anchor, extra + anchor, "extractor test anchor"), encoding="utf-8")

sabr = Path("third_party/LevyraExtractor/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/sabr/YoutubeSabrFormat.java")
text = sabr.read_text(encoding="utf-8")
start = text.index("    /**\n     * Identity used to prevent state or initialization bytes from leaking between variants that")
end = text.index("    @Nonnull\n    public String formatIdentity()", start)
sabr.write_text(text[:start] + text[end:], encoding="utf-8")
