org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
systemProp.org.gradle.internal.http.socketTimeout=600000
systemProp.org.gradle.internal.http.connectionTimeout=120000
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.enableR8.fullMode=true
android.onlyEnableUnitTestForTheTestedBuildType=false
kotlin.code.style=official
levyraVersionName=2.5.3
levyraVersionCode=2050300
# Release trigger for Android 2.5.3
