package com.luc4n3x.levyra.ui.i18n

internal data class PlaybackBufferCopy(
    val title: String,
    val description: String,
    val automatic: String,
    val custom: String,
    val automaticDetail: String,
    val customDetail: String,
    val minimum: String,
    val maximum: String,
    val start: String,
    val afterInterruption: String,
    val presets: String,
    val reduced: String,
    val balanced: String,
    val high: String,
    val restoreAutomatic: String
)

private fun bufferCopy(vararg values: String): PlaybackBufferCopy {
    require(values.size == 15)
    return PlaybackBufferCopy(
        title = values[0],
        description = values[1],
        automatic = values[2],
        custom = values[3],
        automaticDetail = values[4],
        customDetail = values[5],
        minimum = values[6],
        maximum = values[7],
        start = values[8],
        afterInterruption = values[9],
        presets = values[10],
        reduced = values[11],
        balanced = values[12],
        high = values[13],
        restoreAutomatic = values[14]
    )
}

private val playbackBufferCopies = mapOf(
    "en" to bufferCopy("Playback buffer", "Choose how much media Levyra prepares ahead. Larger buffers may handle interruptions better, but can use more memory and delay startup.", "Automatic", "Custom", "Uses the same adaptive buffering Levyra normally selects for this device.", "Saved now and applied the next time the player starts. Current playback is not interrupted; recovery may temporarily extend the buffer.", "Minimum buffer", "Maximum buffer", "Startup buffer", "Buffer after interruption", "Presets", "Reduced", "Balanced", "High", "Restore automatic"),
    "it" to bufferCopy("Buffer di riproduzione", "Scegli quanti dati Levyra prepara in anticipo. Buffer più ampi possono gestire meglio le interruzioni, ma usare più memoria e ritardare l’avvio.", "Automatico", "Personalizzato", "Usa lo stesso buffering adattivo che Levyra seleziona normalmente per questo dispositivo.", "Salvato subito e applicato al prossimo avvio del player. La riproduzione corrente non viene interrotta; il recupero può ampliare temporaneamente il buffer.", "Buffer minimo", "Buffer massimo", "Buffer iniziale", "Buffer dopo un’interruzione", "Preset", "Ridotto", "Bilanciato", "Alto", "Ripristina automatico"),
    "es" to bufferCopy("Búfer de reproducción", "Elige cuántos datos prepara Levyra por adelantado. Un búfer mayor puede soportar mejor las interrupciones, pero usar más memoria y retrasar el inicio.", "Automático", "Personalizado", "Usa el mismo búfer adaptativo que Levyra selecciona normalmente para este dispositivo.", "Se guarda ahora y se aplica la próxima vez que se inicie el reproductor. La reproducción actual no se interrumpe; la recuperación puede ampliar temporalmente el búfer.", "Búfer mínimo", "Búfer máximo", "Búfer inicial", "Búfer tras una interrupción", "Preajustes", "Reducido", "Equilibrado", "Alto", "Restaurar automático"),
    "fr" to bufferCopy("Mémoire tampon de lecture", "Choisissez la quantité de média préparée à l’avance par Levyra. Une mémoire tampon plus grande peut mieux résister aux interruptions, mais utiliser davantage de mémoire et retarder le démarrage.", "Automatique", "Personnalisé", "Utilise la même mise en mémoire tampon adaptative que Levyra choisit normalement pour cet appareil.", "Enregistré immédiatement et appliqué au prochain démarrage du lecteur. La lecture en cours n’est pas interrompue ; la récupération peut agrandir temporairement la mémoire tampon.", "Tampon minimal", "Tampon maximal", "Tampon de démarrage", "Tampon après interruption", "Préréglages", "Réduit", "Équilibré", "Élevé", "Rétablir le mode automatique"),
    "de" to bufferCopy("Wiedergabepuffer", "Lege fest, wie viele Mediendaten Levyra im Voraus lädt. Größere Puffer können Unterbrechungen besser abfangen, benötigen aber mehr Speicher und können den Start verzögern.", "Automatisch", "Benutzerdefiniert", "Verwendet dieselbe adaptive Pufferung, die Levyra normalerweise für dieses Gerät auswählt.", "Wird jetzt gespeichert und beim nächsten Start des Players angewendet. Die aktuelle Wiedergabe wird nicht unterbrochen; zur Wiederherstellung kann der Puffer vorübergehend erweitert werden.", "Mindestpuffer", "Maximalpuffer", "Startpuffer", "Puffer nach Unterbrechung", "Voreinstellungen", "Reduziert", "Ausgewogen", "Hoch", "Automatik wiederherstellen"),
    "pt" to bufferCopy("Buffer de reprodução", "Escolha quantos dados o Levyra prepara antecipadamente. Um buffer maior pode lidar melhor com interrupções, mas usar mais memória e atrasar o início.", "Automático", "Personalizado", "Usa o mesmo buffer adaptativo que o Levyra normalmente seleciona para este dispositivo.", "É guardado agora e aplicado na próxima inicialização do leitor. A reprodução atual não é interrompida; a recuperação pode aumentar temporariamente o buffer.", "Buffer mínimo", "Buffer máximo", "Buffer inicial", "Buffer após interrupção", "Predefinições", "Reduzido", "Equilibrado", "Alto", "Restaurar automático"),
    "nl" to bufferCopy("Afspeelbuffer", "Kies hoeveel media Levyra vooraf voorbereidt. Grotere buffers kunnen onderbrekingen beter opvangen, maar gebruiken meer geheugen en kunnen de start vertragen.", "Automatisch", "Aangepast", "Gebruikt dezelfde adaptieve buffering die Levyra normaal voor dit apparaat kiest.", "Wordt nu opgeslagen en toegepast wanneer de speler de volgende keer start. De huidige weergave wordt niet onderbroken; bij herstel kan de buffer tijdelijk worden vergroot.", "Minimale buffer", "Maximale buffer", "Startbuffer", "Buffer na onderbreking", "Voorinstellingen", "Klein", "Gebalanceerd", "Groot", "Automatisch herstellen"),
    "pl" to bufferCopy("Bufor odtwarzania", "Wybierz, ile danych Levyra przygotowuje z wyprzedzeniem. Większy bufor może lepiej radzić sobie z przerwami, ale zużywa więcej pamięci i może opóźniać start.", "Automatyczny", "Niestandardowy", "Używa tego samego adaptacyjnego buforowania, które Levyra zwykle dobiera dla tego urządzenia.", "Ustawienie jest zapisywane teraz i stosowane przy następnym uruchomieniu odtwarzacza. Bieżące odtwarzanie nie zostanie przerwane; odzyskiwanie może chwilowo zwiększyć bufor.", "Bufor minimalny", "Bufor maksymalny", "Bufor startowy", "Bufor po przerwie", "Ustawienia wstępne", "Mały", "Zrównoważony", "Duży", "Przywróć automatyczny"),
    "ro" to bufferCopy("Memorie tampon pentru redare", "Alege cât conținut pregătește Levyra în avans. O memorie tampon mai mare poate gestiona mai bine întreruperile, dar folosește mai multă memorie și poate întârzia pornirea.", "Automat", "Personalizat", "Folosește aceeași tamponare adaptivă pe care Levyra o selectează în mod normal pentru acest dispozitiv.", "Se salvează acum și se aplică la următoarea pornire a playerului. Redarea curentă nu este întreruptă; recuperarea poate mări temporar memoria tampon.", "Tampon minim", "Tampon maxim", "Tampon la pornire", "Tampon după întrerupere", "Presetări", "Redus", "Echilibrat", "Ridicat", "Restabilește modul automat"),
    "el" to bufferCopy("Προσωρινή μνήμη αναπαραγωγής", "Επιλέξτε πόσα δεδομένα προετοιμάζει εκ των προτέρων το Levyra. Η μεγαλύτερη προσωρινή μνήμη μπορεί να αντιμετωπίζει καλύτερα τις διακοπές, αλλά χρησιμοποιεί περισσότερη μνήμη και μπορεί να καθυστερεί την έναρξη.", "Αυτόματα", "Προσαρμοσμένα", "Χρησιμοποιεί την ίδια προσαρμοστική προσωρινή μνήμη που επιλέγει κανονικά το Levyra για αυτήν τη συσκευή.", "Αποθηκεύεται τώρα και εφαρμόζεται στην επόμενη εκκίνηση του προγράμματος αναπαραγωγής. Η τρέχουσα αναπαραγωγή δεν διακόπτεται· η ανάκτηση μπορεί να αυξήσει προσωρινά τη μνήμη.", "Ελάχιστη μνήμη", "Μέγιστη μνήμη", "Μνήμη εκκίνησης", "Μνήμη μετά από διακοπή", "Προεπιλογές", "Μειωμένη", "Ισορροπημένη", "Υψηλή", "Επαναφορά αυτόματης λειτουργίας"),
    "sv" to bufferCopy("Uppspelningsbuffert", "Välj hur mycket media Levyra förbereder i förväg. En större buffert kan hantera avbrott bättre, men använder mer minne och kan fördröja starten.", "Automatisk", "Anpassad", "Använder samma adaptiva buffring som Levyra normalt väljer för den här enheten.", "Sparas nu och används nästa gång spelaren startar. Den pågående uppspelningen avbryts inte; återställning kan tillfälligt utöka bufferten.", "Minsta buffert", "Största buffert", "Startbuffert", "Buffert efter avbrott", "Förinställningar", "Minskad", "Balanserad", "Hög", "Återställ automatisk"),
    "da" to bufferCopy("Afspilningsbuffer", "Vælg, hvor meget medie Levyra forbereder på forhånd. En større buffer kan håndtere afbrydelser bedre, men bruger mere hukommelse og kan forsinke starten.", "Automatisk", "Tilpasset", "Bruger den samme adaptive buffering, som Levyra normalt vælger til denne enhed.", "Gemmes nu og anvendes, næste gang afspilleren starter. Den aktuelle afspilning afbrydes ikke; genoprettelse kan midlertidigt udvide bufferen.", "Mindste buffer", "Største buffer", "Startbuffer", "Buffer efter afbrydelse", "Forudindstillinger", "Reduceret", "Balanceret", "Høj", "Gendan automatisk"),
    "cs" to bufferCopy("Vyrovnávací paměť přehrávání", "Zvolte, kolik médií má Levyra připravit dopředu. Větší vyrovnávací paměť může lépe zvládat výpadky, ale využívá více paměti a může zpozdit spuštění.", "Automaticky", "Vlastní", "Používá stejné adaptivní ukládání do vyrovnávací paměti, které Levyra pro toto zařízení běžně volí.", "Nastavení se uloží nyní a použije při příštím spuštění přehrávače. Aktuální přehrávání se nepřeruší; při obnovení se může paměť dočasně zvětšit.", "Minimální paměť", "Maximální paměť", "Paměť při spuštění", "Paměť po přerušení", "Předvolby", "Nízká", "Vyvážená", "Vysoká", "Obnovit automatické nastavení"),
    "sk" to bufferCopy("Vyrovnávacia pamäť prehrávania", "Vyberte, koľko médií má Levyra pripraviť vopred. Väčšia vyrovnávacia pamäť môže lepšie zvládať výpadky, ale využíva viac pamäte a môže oddialiť spustenie.", "Automaticky", "Vlastné", "Používa rovnaké adaptívne ukladanie do vyrovnávacej pamäte, ktoré Levyra bežne vyberá pre toto zariadenie.", "Nastavenie sa uloží teraz a použije pri ďalšom spustení prehrávača. Aktuálne prehrávanie sa nepreruší; pri obnove sa môže pamäť dočasne zväčšiť.", "Minimálna pamäť", "Maximálna pamäť", "Pamäť pri spustení", "Pamäť po prerušení", "Predvoľby", "Nízka", "Vyvážená", "Vysoká", "Obnoviť automatické nastavenie"),
    "hr" to bufferCopy("Međuspremnik reprodukcije", "Odaberite koliko medija Levyra priprema unaprijed. Veći međuspremnik može bolje podnijeti prekide, ali troši više memorije i može odgoditi početak.", "Automatski", "Prilagođeno", "Koristi isto prilagodljivo spremanje koje Levyra uobičajeno odabire za ovaj uređaj.", "Postavka se sprema sada i primjenjuje pri sljedećem pokretanju reproduktora. Trenutačna reprodukcija neće se prekinuti; oporavak može privremeno povećati međuspremnik.", "Najmanji međuspremnik", "Najveći međuspremnik", "Početni međuspremnik", "Međuspremnik nakon prekida", "Zadane postavke", "Smanjeno", "Uravnoteženo", "Visoko", "Vrati automatsko"),
    "bg" to bufferCopy("Буфер за възпроизвеждане", "Изберете колко медийни данни Levyra подготвя предварително. По-големият буфер може да се справя по-добре с прекъсвания, но използва повече памет и може да забави старта.", "Автоматично", "Персонализирано", "Използва същото адаптивно буфериране, което Levyra обичайно избира за това устройство.", "Запазва се сега и се прилага при следващото стартиране на плейъра. Текущото възпроизвеждане не се прекъсва; възстановяването може временно да увеличи буфера.", "Минимален буфер", "Максимален буфер", "Начален буфер", "Буфер след прекъсване", "Готови настройки", "Нисък", "Балансиран", "Висок", "Възстанови автоматично"),
    "hu" to bufferCopy("Lejátszási puffer", "Válaszd ki, mennyi médiát készítsen elő a Levyra. A nagyobb puffer jobban kezelheti a megszakításokat, de több memóriát használ, és késleltetheti az indulást.", "Automatikus", "Egyéni", "Ugyanazt az adaptív pufferelést használja, amelyet a Levyra normál esetben ehhez az eszközhöz választ.", "A beállítás most mentésre kerül, és a lejátszó következő indításakor lép életbe. A jelenlegi lejátszás nem szakad meg; a helyreállítás ideiglenesen növelheti a puffert.", "Minimális puffer", "Maximális puffer", "Indítási puffer", "Puffer megszakítás után", "Előbeállítások", "Csökkentett", "Kiegyensúlyozott", "Magas", "Automatikus visszaállítása"),
    "fi" to bufferCopy("Toistopuskuri", "Valitse, kuinka paljon mediaa Levyra valmistelee etukäteen. Suurempi puskuri voi kestää katkoja paremmin, mutta käyttää enemmän muistia ja voi viivästyttää käynnistystä.", "Automaattinen", "Mukautettu", "Käyttää samaa mukautuvaa puskurointia, jonka Levyra tavallisesti valitsee tälle laitteelle.", "Tallennetaan nyt ja otetaan käyttöön, kun soitin käynnistyy seuraavan kerran. Nykyistä toistoa ei keskeytetä; palautus voi kasvattaa puskuria tilapäisesti.", "Vähimmäispuskuri", "Enimmäispuskuri", "Käynnistyspuskuri", "Puskuri katkon jälkeen", "Esiasetukset", "Pieni", "Tasapainoinen", "Suuri", "Palauta automaattinen"),
    "et" to bufferCopy("Taasesituse puhver", "Valige, kui palju meediumit Levyra ette valmistab. Suurem puhver võib katkestustega paremini toime tulla, kuid kasutab rohkem mälu ja võib käivitumist viivitada.", "Automaatne", "Kohandatud", "Kasutab sama kohanduvat puhverdamist, mille Levyra tavaliselt selle seadme jaoks valib.", "Salvestatakse kohe ja rakendatakse mängija järgmisel käivitamisel. Praegust taasesitust ei katkestata; taastamine võib puhvrit ajutiselt suurendada.", "Minimaalne puhver", "Maksimaalne puhver", "Käivituspuhver", "Puhver pärast katkestust", "Eelseaded", "Väike", "Tasakaalustatud", "Suur", "Taasta automaatne"),
    "nb" to bufferCopy("Avspillingsbuffer", "Velg hvor mye media Levyra forbereder på forhånd. En større buffer kan håndtere avbrudd bedre, men bruker mer minne og kan forsinke oppstarten.", "Automatisk", "Tilpasset", "Bruker den samme adaptive bufringen som Levyra vanligvis velger for denne enheten.", "Lagres nå og brukes neste gang spilleren starter. Gjeldende avspilling avbrytes ikke; gjenoppretting kan midlertidig utvide bufferen.", "Minste buffer", "Største buffer", "Oppstartsbuffer", "Buffer etter avbrudd", "Forhåndsinnstillinger", "Redusert", "Balansert", "Høy", "Gjenopprett automatisk"),
    "ca" to bufferCopy("Memòria intermèdia de reproducció", "Tria quants continguts prepara Levyra per endavant. Una memòria més gran pot gestionar millor les interrupcions, però utilitza més memòria i pot retardar l’inici.", "Automàtic", "Personalitzat", "Utilitza la mateixa memòria intermèdia adaptativa que Levyra selecciona normalment per a aquest dispositiu.", "Es desa ara i s’aplica la pròxima vegada que s’inicia el reproductor. La reproducció actual no s’interromp; la recuperació pot ampliar temporalment la memòria.", "Memòria mínima", "Memòria màxima", "Memòria d’inici", "Memòria després d’una interrupció", "Predefinits", "Reduït", "Equilibrat", "Alt", "Restaura l’automàtic"),
    "uk" to bufferCopy("Буфер відтворення", "Виберіть, скільки медіаданих Levyra готує заздалегідь. Більший буфер може краще долати переривання, але використовує більше пам’яті й може затримувати запуск.", "Автоматично", "Власні налаштування", "Використовує те саме адаптивне буферування, яке Levyra зазвичай вибирає для цього пристрою.", "Налаштування зберігається зараз і застосовується під час наступного запуску програвача. Поточне відтворення не переривається; відновлення може тимчасово збільшити буфер.", "Мінімальний буфер", "Максимальний буфер", "Початковий буфер", "Буфер після переривання", "Набори", "Зменшений", "Збалансований", "Високий", "Відновити автоматичний режим"),
    "ru" to bufferCopy("Буфер воспроизведения", "Выберите, сколько медиаданных Levyra подготавливает заранее. Больший буфер может лучше справляться с прерываниями, но использует больше памяти и может задерживать запуск.", "Автоматически", "Вручную", "Использует ту же адаптивную буферизацию, которую Levyra обычно выбирает для этого устройства.", "Настройка сохраняется сейчас и применяется при следующем запуске проигрывателя. Текущее воспроизведение не прерывается; при восстановлении буфер может временно увеличиваться.", "Минимальный буфер", "Максимальный буфер", "Начальный буфер", "Буфер после прерывания", "Предустановки", "Малый", "Сбалансированный", "Высокий", "Восстановить автоматически"),
    "tr" to bufferCopy("Oynatma arabelleği", "Levyra’nın ne kadar medyayı önceden hazırlayacağını seçin. Daha büyük arabellek kesintileri daha iyi karşılayabilir, ancak daha fazla bellek kullanır ve başlangıcı geciktirebilir.", "Otomatik", "Özel", "Levyra’nın normalde bu cihaz için seçtiği uyarlanabilir arabelleği kullanır.", "Şimdi kaydedilir ve oynatıcı bir sonraki kez başladığında uygulanır. Geçerli oynatma kesilmez; kurtarma sırasında arabellek geçici olarak büyüyebilir.", "En düşük arabellek", "En yüksek arabellek", "Başlangıç arabelleği", "Kesinti sonrası arabellek", "Ön ayarlar", "Düşük", "Dengeli", "Yüksek", "Otomatiği geri yükle"),
    "ar" to bufferCopy("ذاكرة التخزين المؤقت للتشغيل", "اختر مقدار الوسائط التي يجهزها Levyra مسبقًا. قد تتعامل الذاكرة الأكبر مع الانقطاعات بصورة أفضل، لكنها تستخدم ذاكرة أكثر وقد تؤخر بدء التشغيل.", "تلقائي", "مخصص", "يستخدم التخزين المؤقت التكيفي نفسه الذي يختاره Levyra عادةً لهذا الجهاز.", "يُحفظ الآن ويُطبق عند بدء المشغّل في المرة القادمة. لن يتوقف التشغيل الحالي؛ وقد تزيد الاستعادة حجم الذاكرة مؤقتًا.", "الحد الأدنى للذاكرة", "الحد الأقصى للذاكرة", "ذاكرة بدء التشغيل", "الذاكرة بعد الانقطاع", "إعدادات مسبقة", "منخفض", "متوازن", "مرتفع", "استعادة الوضع التلقائي"),
    "fa" to bufferCopy("بافر پخش", "مقدار رسانه‌ای را که Levyra از قبل آماده می‌کند انتخاب کنید. بافر بزرگ‌تر ممکن است وقفه‌ها را بهتر مدیریت کند، اما حافظه بیشتری مصرف می‌کند و می‌تواند شروع پخش را به تأخیر بیندازد.", "خودکار", "سفارشی", "از همان بافر تطبیقی استفاده می‌کند که Levyra معمولاً برای این دستگاه انتخاب می‌کند.", "اکنون ذخیره می‌شود و در شروع بعدی پخش‌کننده اعمال خواهد شد. پخش فعلی قطع نمی‌شود؛ بازیابی ممکن است بافر را موقتاً افزایش دهد.", "حداقل بافر", "حداکثر بافر", "بافر شروع", "بافر پس از وقفه", "پیش‌تنظیم‌ها", "کم", "متعادل", "زیاد", "بازگردانی حالت خودکار"),
    "zh" to bufferCopy("播放缓冲区", "选择 Levyra 提前准备的媒体量。较大的缓冲区可能更好地应对中断，但会占用更多内存，并可能延迟开始播放。", "自动", "自定义", "使用 Levyra 通常为此设备选择的相同自适应缓冲逻辑。", "设置会立即保存，并在播放器下次启动时应用。当前播放不会中断；恢复期间可能会暂时扩大缓冲区。", "最小缓冲", "最大缓冲", "启动缓冲", "中断后缓冲", "预设", "较低", "均衡", "较高", "恢复自动模式"),
    "zh-Hant" to bufferCopy("播放緩衝區", "選擇 Levyra 預先準備的媒體量。較大的緩衝區可能更能應付中斷，但會使用更多記憶體，並可能延遲開始播放。", "自動", "自訂", "使用 Levyra 通常為此裝置選擇的相同自適應緩衝邏輯。", "設定會立即儲存，並在播放器下次啟動時套用。目前的播放不會中斷；復原期間可能會暫時擴大緩衝區。", "最小緩衝", "最大緩衝", "啟動緩衝", "中斷後緩衝", "預設", "較低", "均衡", "較高", "恢復自動模式"),
    "ja" to bufferCopy("再生バッファ", "Levyra が事前に準備するメディア量を選択します。バッファを大きくすると中断に強くなる場合がありますが、メモリ使用量が増え、再生開始が遅れることがあります。", "自動", "カスタム", "Levyra が通常このデバイスに選択するものと同じ適応型バッファを使用します。", "設定はすぐに保存され、次回プレーヤーを起動したときに適用されます。現在の再生は中断されません。復旧時にはバッファが一時的に拡張される場合があります。", "最小バッファ", "最大バッファ", "開始時のバッファ", "中断後のバッファ", "プリセット", "小", "バランス", "大", "自動に戻す"),
    "ko" to bufferCopy("재생 버퍼", "Levyra가 미리 준비할 미디어 양을 선택하세요. 버퍼가 크면 끊김에 더 잘 대응할 수 있지만 메모리를 더 사용하고 재생 시작이 늦어질 수 있습니다.", "자동", "사용자 설정", "Levyra가 일반적으로 이 기기에 선택하는 것과 동일한 적응형 버퍼링을 사용합니다.", "지금 저장되며 다음에 플레이어가 시작될 때 적용됩니다. 현재 재생은 중단되지 않으며 복구 중 버퍼가 일시적으로 늘어날 수 있습니다.", "최소 버퍼", "최대 버퍼", "시작 버퍼", "중단 후 버퍼", "프리셋", "낮음", "균형", "높음", "자동 모드 복원"),
    "hi" to bufferCopy("प्लेबैक बफ़र", "चुनें कि Levyra कितने मीडिया को पहले से तैयार करे। बड़ा बफ़र रुकावटों को बेहतर संभाल सकता है, लेकिन अधिक मेमोरी लेता है और शुरुआत में देरी कर सकता है।", "स्वचालित", "कस्टम", "उसी अनुकूली बफ़रिंग का उपयोग करता है जिसे Levyra सामान्यतः इस डिवाइस के लिए चुनता है।", "अभी सहेजा जाता है और प्लेयर के अगली बार शुरू होने पर लागू होता है। मौजूदा प्लेबैक नहीं रुकेगा; रिकवरी के समय बफ़र अस्थायी रूप से बढ़ सकता है।", "न्यूनतम बफ़र", "अधिकतम बफ़र", "शुरुआती बफ़र", "रुकावट के बाद बफ़र", "प्रीसेट", "कम", "संतुलित", "अधिक", "स्वचालित मोड बहाल करें"),
    "id" to bufferCopy("Buffer pemutaran", "Pilih jumlah media yang disiapkan Levyra sebelumnya. Buffer yang lebih besar mungkin lebih tahan terhadap gangguan, tetapi memakai lebih banyak memori dan dapat menunda pemutaran.", "Otomatis", "Kustom", "Menggunakan buffer adaptif yang sama seperti yang biasanya dipilih Levyra untuk perangkat ini.", "Disimpan sekarang dan diterapkan saat pemutar dimulai lagi. Pemutaran saat ini tidak terganggu; pemulihan dapat memperbesar buffer untuk sementara.", "Buffer minimum", "Buffer maksimum", "Buffer awal", "Buffer setelah gangguan", "Prasetel", "Rendah", "Seimbang", "Tinggi", "Pulihkan otomatis"),
    "ms" to bufferCopy("Penimbal main balik", "Pilih jumlah media yang Levyra sediakan lebih awal. Penimbal yang lebih besar mungkin lebih baik menangani gangguan, tetapi menggunakan lebih banyak memori dan boleh melambatkan permulaan.", "Automatik", "Tersuai", "Menggunakan penimbalan adaptif yang sama seperti yang biasanya dipilih Levyra untuk peranti ini.", "Disimpan sekarang dan digunakan apabila pemain dimulakan lagi. Main balik semasa tidak terganggu; pemulihan boleh membesarkan penimbal buat sementara waktu.", "Penimbal minimum", "Penimbal maksimum", "Penimbal permulaan", "Penimbal selepas gangguan", "Pratetap", "Rendah", "Seimbang", "Tinggi", "Pulihkan automatik"),
    "vi" to bufferCopy("Bộ đệm phát", "Chọn lượng nội dung Levyra chuẩn bị trước. Bộ đệm lớn hơn có thể xử lý gián đoạn tốt hơn, nhưng dùng nhiều bộ nhớ hơn và có thể làm chậm lúc bắt đầu.", "Tự động", "Tùy chỉnh", "Dùng cùng cơ chế đệm thích ứng mà Levyra thường chọn cho thiết bị này.", "Được lưu ngay và áp dụng vào lần khởi động trình phát tiếp theo. Nội dung đang phát không bị gián đoạn; quá trình khôi phục có thể tạm thời tăng bộ đệm.", "Bộ đệm tối thiểu", "Bộ đệm tối đa", "Bộ đệm khởi động", "Bộ đệm sau gián đoạn", "Cấu hình sẵn", "Thấp", "Cân bằng", "Cao", "Khôi phục tự động"),
    "th" to bufferCopy("บัฟเฟอร์การเล่น", "เลือกปริมาณสื่อที่ Levyra เตรียมไว้ล่วงหน้า บัฟเฟอร์ที่ใหญ่ขึ้นอาจรับมือกับการสะดุดได้ดีขึ้น แต่ใช้หน่วยความจำมากขึ้นและอาจทำให้เริ่มเล่นช้าลง", "อัตโนมัติ", "กำหนดเอง", "ใช้การบัฟเฟอร์แบบปรับตัวเดียวกับที่ Levyra เลือกให้กับอุปกรณ์นี้ตามปกติ", "บันทึกทันทีและนำไปใช้เมื่อโปรแกรมเล่นเริ่มทำงานครั้งถัดไป การเล่นปัจจุบันจะไม่หยุดชะงัก และการกู้คืนอาจเพิ่มบัฟเฟอร์ชั่วคราว", "บัฟเฟอร์ขั้นต่ำ", "บัฟเฟอร์สูงสุด", "บัฟเฟอร์เริ่มต้น", "บัฟเฟอร์หลังการสะดุด", "ค่าที่ตั้งไว้", "ต่ำ", "สมดุล", "สูง", "คืนค่าอัตโนมัติ"),
    "fil" to bufferCopy("Buffer ng playback", "Piliin kung gaano karaming media ang ihahanda nang maaga ng Levyra. Maaaring mas mahusay sa mga pagkaantala ang mas malaking buffer, ngunit gagamit ito ng mas maraming memory at maaaring magpatagal sa pagsisimula.", "Awtomatiko", "Custom", "Ginagamit ang parehong adaptive buffering na karaniwang pinipili ng Levyra para sa device na ito.", "Sine-save ngayon at ilalapat sa susunod na pagsisimula ng player. Hindi maaantala ang kasalukuyang playback; maaaring pansamantalang palakihin ng recovery ang buffer.", "Pinakamababang buffer", "Pinakamataas na buffer", "Panimulang buffer", "Buffer pagkatapos ng pagkaantala", "Mga preset", "Mababa", "Balansyado", "Mataas", "Ibalik ang awtomatiko"),
    "he" to bufferCopy("מאגר הפעלה", "בחרו כמה מדיה Levyra תכין מראש. מאגר גדול יותר עשוי להתמודד טוב יותר עם הפרעות, אך צורך יותר זיכרון ועלול לעכב את תחילת ההפעלה.", "אוטומטי", "מותאם אישית", "משתמש באותו אגירה מסתגלת ש-Levyra בוחרת בדרך כלל עבור המכשיר הזה.", "ההגדרה נשמרת כעת ומוחלת בפעם הבאה שהנגן יופעל. ההפעלה הנוכחית לא תיפסק; השחזור עשוי להגדיל זמנית את המאגר.", "מאגר מינימלי", "מאגר מרבי", "מאגר התחלה", "מאגר לאחר הפרעה", "הגדרות קבועות מראש", "נמוך", "מאוזן", "גבוה", "שחזור מצב אוטומטי")
)

internal fun playbackBufferCopy(code: String): PlaybackBufferCopy =
    localizedValueOrEnglish(playbackBufferCopies, code)

internal fun playbackBufferLocalizationCodes(): Set<String> = playbackBufferCopies.keys
