package com.luc4n3x.levyra.ui.i18n

data class LevyraAutomationCopy(
    val spotifyCsvTitle: String,
    val spotifyCsvSubtitle: String,
    val chooseCsv: String,
    val playlistNameLabel: String,
    val importing: String,
    val matched: String,
    val unmatched: String,
    val importFailed: String,
    val fadeOut: String,
    val fadeOutSubtitle: String,
    val bedtime: String,
    val bedtimeSubtitle: String,
    val startTime: String,
    val duration: String,
    val repeat: String,
    val automation: String,
    val bluetoothResume: String,
    val bluetoothResumeSubtitle: String,
    val pauseOnMute: String,
    val pauseOnMuteSubtitle: String,
    val autoDownloadFavorites: String,
    val autoDownloadFavoritesSubtitle: String,
    val skipUnrecoverable: String,
    val skipUnrecoverableSubtitle: String
)

fun LevyraStrings.automationCopy(): LevyraAutomationCopy = when (code) {
    "it" -> LevyraAutomationCopy("Importa da Spotify", "Crea una playlist da un CSV esportato da Spotify", "Scegli CSV", "Nome playlist", "Importazione…", "Trovati", "Non trovati", "Importazione non riuscita", "Dissolvenza", "Abbassa il volume prima dello stop", "Programma notturno", "Avvia lo sleep timer automaticamente", "Ora di inizio", "Durata", "Ripeti", "Automazioni", "Riprendi la riproduzione al riconnettersi del Bluetooth", "Solo dopo una pausa causata dalla perdita del dispositivo audio", "Metti in pausa quando il volume è a zero", "Mette in pausa quando il volume multimediale arriva a zero", "Scarica automaticamente i brani preferiti", "Mette in coda un download quando aggiungi un preferito", "Salta il brano dopo un errore irreversibile", "Solo dopo il fallimento dei normali tentativi di recupero")
    "es" -> LevyraAutomationCopy("Importar desde Spotify", "Crea una playlist desde un CSV exportado de Spotify", "Elegir CSV", "Nombre de la playlist", "Importando…", "Encontrados", "No encontrados", "Error al importar", "Fundido", "Baja el volumen antes de detener la reproducción", "Programación nocturna", "Inicia el temporizador automáticamente", "Hora de inicio", "Duración", "Repetir", "Automatizaciones", "Reanudar la reproducción al reconectar Bluetooth", "Solo tras una pausa causada por perder el dispositivo de audio", "Pausar cuando el volumen esté silenciado", "Pausa la reproducción cuando el volumen llega a cero", "Descargar automáticamente las canciones favoritas", "Pone una descarga en cola al marcar un favorito", "Saltar la pista tras un error irrecuperable", "Solo después de fallar los intentos normales de recuperación")
    "fr" -> LevyraAutomationCopy("Importer depuis Spotify", "Créez une playlist à partir d’un CSV exporté de Spotify", "Choisir un CSV", "Nom de la playlist", "Importation…", "Trouvés", "Non trouvés", "Échec de l’importation", "Fondu", "Baisse le volume avant l’arrêt de la lecture", "Programmation nocturne", "Démarre la minuterie automatiquement", "Heure de début", "Durée", "Répéter", "Automatisations", "Reprendre la lecture à la reconnexion Bluetooth", "Uniquement après une pause due à la perte du périphérique audio", "Mettre en pause quand le volume est coupé", "Met la lecture en pause quand le volume atteint zéro", "Télécharger automatiquement les titres aimés", "Met un téléchargement en file quand vous aimez un titre", "Passer le titre après une erreur irrécupérable", "Uniquement après l’échec des tentatives de récupération")
    "de" -> LevyraAutomationCopy("Aus Spotify importieren", "Erstelle eine Playlist aus einer exportierten Spotify-CSV", "CSV wählen", "Playlist-Name", "Import läuft…", "Gefunden", "Nicht gefunden", "Import fehlgeschlagen", "Ausblenden", "Senkt die Lautstärke vor dem Stopp", "Nachtplan", "Startet den Sleeptimer automatisch", "Startzeit", "Dauer", "Wiederholen", "Automatisierungen", "Wiedergabe bei Bluetooth-Verbindung fortsetzen", "Nur nach einer Pause durch Verlust des Audiogeräts", "Bei stummgeschaltetem Ton pausieren", "Pausiert, wenn die Medienlautstärke null erreicht", "Gelikte Titel automatisch herunterladen", "Reiht einen Download ein, wenn du einen Titel likest", "Titel nach nicht behebbarem Fehler überspringen", "Nur nachdem die normalen Wiederherstellungsversuche fehlgeschlagen sind")
    "pt" -> LevyraAutomationCopy("Importar do Spotify", "Crie uma playlist a partir de um CSV exportado do Spotify", "Escolher CSV", "Nome da playlist", "A importar…", "Encontrados", "Não encontrados", "Falha na importação", "Fade out", "Baixa o volume antes de parar a reprodução", "Agenda noturna", "Inicia o temporizador automaticamente", "Hora de início", "Duração", "Repetir", "Automatizações", "Retomar a reprodução ao reconectar o Bluetooth", "Apenas após uma pausa causada pela perda do dispositivo de áudio", "Pausar quando o volume estiver mudo", "Pausa a reprodução quando o volume chega a zero", "Transferir automaticamente as músicas favoritas", "Coloca uma transferência em fila ao marcar um favorito", "Saltar a faixa após erro irrecuperável", "Apenas depois de falharem as tentativas normais de recuperação")
    "nl" -> LevyraAutomationCopy("Importeren uit Spotify", "Maak een afspeellijst van een geëxporteerde Spotify-CSV", "Kies CSV", "Naam afspeellijst", "Bezig met importeren…", "Gevonden", "Niet gevonden", "Importeren mislukt", "Uitfaden", "Verlaagt het volume voordat het afspelen stopt", "Bedtijdschema", "Start de slaaptimer automatisch", "Starttijd", "Duur", "Herhalen", "Automatiseringen", "Afspelen hervatten bij Bluetooth-herverbinding", "Alleen na een pauze door verlies van het audioapparaat", "Pauzeren bij gedempt volume", "Pauzeert het afspelen als het volume nul bereikt", "Leuk gevonden nummers automatisch downloaden", "Zet een download in de wachtrij als je een nummer leuk vindt", "Nummer overslaan na onherstelbare fout", "Alleen nadat de normale herstelpogingen zijn mislukt")
    "pl" -> LevyraAutomationCopy("Importuj ze Spotify", "Utwórz playlistę z wyeksportowanego pliku CSV ze Spotify", "Wybierz CSV", "Nazwa playlisty", "Importowanie…", "Dopasowane", "Niedopasowane", "Import nie powiódł się", "Wyciszanie", "Obniża głośność przed zatrzymaniem odtwarzania", "Harmonogram nocny", "Automatycznie uruchamia wyłącznik czasowy", "Godzina rozpoczęcia", "Czas trwania", "Powtarzaj", "Automatyzacje", "Wznów odtwarzanie po ponownym połączeniu Bluetooth", "Tylko po pauzie spowodowanej utratą urządzenia audio", "Wstrzymaj przy wyciszeniu", "Wstrzymuje odtwarzanie, gdy głośność multimediów spadnie do zera", "Automatycznie pobieraj polubione utwory", "Dodaje pobieranie do kolejki po polubieniu utworu", "Pomiń utwór po nieodwracalnym błędzie", "Tylko po niepowodzeniu zwykłych prób odzyskiwania")
    "ro" -> LevyraAutomationCopy("Importă din Spotify", "Creează un playlist dintr-un CSV exportat din Spotify", "Alege CSV", "Nume playlist", "Se importă…", "Găsite", "Negăsite", "Importul a eșuat", "Estompare", "Reduce volumul înainte de oprirea redării", "Program de noapte", "Pornește automat cronometrul de somn", "Ora de început", "Durată", "Repetă", "Automatizări", "Reia redarea la reconectarea Bluetooth", "Doar după o pauză cauzată de pierderea dispozitivului audio", "Pune pauză când volumul este oprit", "Pune pauză când volumul media ajunge la zero", "Descarcă automat melodiile apreciate", "Adaugă o descărcare în coadă când apreciezi o melodie", "Sari peste piesă după o eroare irecuperabilă", "Doar după eșecul încercărilor normale de recuperare")
    "el" -> LevyraAutomationCopy("Εισαγωγή από Spotify", "Δημιούργησε λίστα από εξαγόμενο CSV του Spotify", "Επιλογή CSV", "Όνομα λίστας", "Εισαγωγή…", "Βρέθηκαν", "Δεν βρέθηκαν", "Η εισαγωγή απέτυχε", "Σταδιακή σίγαση", "Μειώνει την ένταση πριν σταματήσει η αναπαραγωγή", "Πρόγραμμα ύπνου", "Ξεκινά αυτόματα το χρονόμετρο ύπνου", "Ώρα έναρξης", "Διάρκεια", "Επανάληψη", "Αυτοματισμοί", "Συνέχιση αναπαραγωγής με επανασύνδεση Bluetooth", "Μόνο μετά από παύση λόγω απώλειας της συσκευής ήχου", "Παύση όταν η ένταση είναι στο μηδέν", "Κάνει παύση όταν η ένταση πολυμέσων φτάσει στο μηδέν", "Αυτόματη λήψη αγαπημένων", "Προσθέτει λήψη στην ουρά όταν αγαπάς ένα τραγούδι", "Παράλειψη κομματιού μετά από μη ανακτήσιμο σφάλμα", "Μόνο αφού αποτύχουν οι κανονικές προσπάθειες ανάκτησης")
    "sv" -> LevyraAutomationCopy("Importera från Spotify", "Skapa en spellista från en exporterad Spotify-CSV", "Välj CSV", "Spellistans namn", "Importerar…", "Hittade", "Hittades inte", "Importen misslyckades", "Tona ut", "Sänker volymen innan uppspelningen stoppas", "Nattschema", "Startar sovtimern automatiskt", "Starttid", "Längd", "Upprepa", "Automatiseringar", "Återuppta uppspelning vid Bluetooth-återanslutning", "Endast efter en paus orsakad av förlorad ljudenhet", "Pausa när volymen är avstängd", "Pausar uppspelningen när medievolymen når noll", "Ladda ned gillade låtar automatiskt", "Köar en nedladdning när du gillar en låt", "Hoppa över spår efter ett oåterkalleligt fel", "Endast efter att de vanliga återställningsförsöken misslyckats")
    "da" -> LevyraAutomationCopy("Importér fra Spotify", "Opret en playliste fra en eksporteret Spotify-CSV", "Vælg CSV", "Playlistens navn", "Importerer…", "Fundet", "Ikke fundet", "Import mislykkedes", "Fade ud", "Sænker lydstyrken før afspilningen stopper", "Sengetidsplan", "Starter sleeptimeren automatisk", "Starttidspunkt", "Varighed", "Gentag", "Automatiseringer", "Genoptag afspilning ved Bluetooth-genforbindelse", "Kun efter en pause forårsaget af mistet lydenhed", "Sæt på pause ved slået lyd fra", "Sætter afspilningen på pause når medielydstyrken når nul", "Hent automatisk sange du kan lide", "Sætter en download i kø når du synes godt om en sang", "Spring nummer over efter uoprettelig fejl", "Kun efter at de normale gendannelsesforsøg er slået fejl")
    "cs" -> LevyraAutomationCopy("Importovat ze Spotify", "Vytvoř playlist z exportovaného CSV ze Spotify", "Vybrat CSV", "Název playlistu", "Importuje se…", "Nalezeno", "Nenalezeno", "Import selhal", "Ztlumení", "Sníží hlasitost před zastavením přehrávání", "Noční plán", "Automaticky spustí časovač spánku", "Čas začátku", "Trvání", "Opakovat", "Automatizace", "Obnovit přehrávání po opětovném připojení Bluetooth", "Pouze po pauze způsobené ztrátou zvukového zařízení", "Pozastavit při ztlumení", "Pozastaví přehrávání, když hlasitost médií klesne na nulu", "Automaticky stahovat oblíbené skladby", "Zařadí stahování do fronty, když skladbu označíš jako oblíbenou", "Přeskočit skladbu po neopravitelné chybě", "Pouze po selhání běžných pokusů o obnovu")
    "uk" -> LevyraAutomationCopy("Імпорт зі Spotify", "Створіть плейлист з експортованого CSV Spotify", "Вибрати CSV", "Назва плейлиста", "Імпортування…", "Знайдено", "Не знайдено", "Не вдалося імпортувати", "Згасання", "Знижує гучність перед зупинкою відтворення", "Нічний розклад", "Автоматично запускає таймер сну", "Час початку", "Тривалість", "Повторювати", "Автоматизації", "Відновлювати відтворення при повторному підключенні Bluetooth", "Лише після паузи через втрату аудіопристрою", "Пауза при вимкненому звуці", "Ставить на паузу, коли гучність медіа сягає нуля", "Автоматично завантажувати вподобані пісні", "Додає завантаження в чергу, коли ви вподобаєте пісню", "Пропускати трек після невиправної помилки", "Лише після невдалих звичайних спроб відновлення")
    "ru" -> LevyraAutomationCopy("Импорт из Spotify", "Создайте плейлист из экспортированного CSV Spotify", "Выбрать CSV", "Название плейлиста", "Импорт…", "Найдено", "Не найдено", "Не удалось импортировать", "Затухание", "Снижает громкость перед остановкой воспроизведения", "Ночное расписание", "Автоматически запускает таймер сна", "Время начала", "Длительность", "Повторять", "Автоматизации", "Возобновлять воспроизведение при переподключении Bluetooth", "Только после паузы из-за потери аудиоустройства", "Пауза при выключенном звуке", "Ставит на паузу, когда громкость медиа достигает нуля", "Автоматически скачивать понравившиеся песни", "Добавляет загрузку в очередь, когда вы отмечаете песню", "Пропускать трек после неустранимой ошибки", "Только после неудачи обычных попыток восстановления")
    "tr" -> LevyraAutomationCopy("Spotify'dan içe aktar", "Dışa aktarılmış bir Spotify CSV dosyasından çalma listesi oluştur", "CSV seç", "Çalma listesi adı", "İçe aktarılıyor…", "Bulunan", "Bulunamayan", "İçe aktarma başarısız", "Kısılarak bitir", "Çalma durmadan önce sesi kısar", "Gece programı", "Uyku zamanlayıcısını otomatik başlatır", "Başlangıç saati", "Süre", "Tekrarla", "Otomasyonlar", "Bluetooth yeniden bağlandığında çalmayı sürdür", "Yalnızca ses cihazının kaybı nedeniyle duraklatıldıysa", "Ses kapatıldığında duraklat", "Medya sesi sıfıra düştüğünde çalmayı duraklatır", "Beğenilen şarkıları otomatik indir", "Bir şarkıyı beğendiğinde indirmeyi kuyruğa alır", "Kurtarılamayan hatadan sonra parçayı atla", "Yalnızca normal kurtarma denemeleri başarısız olduktan sonra")
    "ar" -> LevyraAutomationCopy("الاستيراد من Spotify", "أنشئ قائمة تشغيل من ملف CSV مُصدَّر من Spotify", "اختر ملف CSV", "اسم قائمة التشغيل", "جارٍ الاستيراد…", "مطابقة", "غير مطابقة", "فشل الاستيراد", "تلاشٍ تدريجي", "يخفض مستوى الصوت قبل إيقاف التشغيل", "جدول النوم", "يبدأ مؤقّت النوم تلقائيًا", "وقت البدء", "المدة", "تكرار", "الأتمتة", "استئناف التشغيل عند إعادة اتصال البلوتوث", "فقط بعد إيقاف مؤقّت ناتج عن فقدان جهاز الصوت", "الإيقاف المؤقت عند كتم الصوت", "يوقف التشغيل مؤقتًا عندما يصل مستوى صوت الوسائط إلى الصفر", "تنزيل الأغاني المفضّلة تلقائيًا", "يضيف تنزيلًا إلى قائمة الانتظار عند إعجابك بأغنية", "تخطّي المقطع بعد خطأ غير قابل للإصلاح", "فقط بعد فشل محاولات الاسترداد المعتادة")
    "zh" -> LevyraAutomationCopy("从 Spotify 导入", "用导出的 Spotify CSV 创建播放列表", "选择 CSV", "播放列表名称", "正在导入…", "已匹配", "未匹配", "导入失败", "淡出", "停止播放前逐渐降低音量", "就寝计划", "自动启动睡眠定时器", "开始时间", "时长", "重复", "自动化", "蓝牙重新连接时恢复播放", "仅在因音频设备丢失而暂停后", "静音时暂停", "媒体音量降为零时暂停播放", "自动下载喜欢的歌曲", "喜欢一首歌时将下载加入队列", "无法恢复的播放错误后跳过", "仅在常规恢复尝试失败后")
    "ja" -> LevyraAutomationCopy("Spotify からインポート", "書き出した Spotify の CSV からプレイリストを作成", "CSV を選択", "プレイリスト名", "インポート中…", "一致", "不一致", "インポートに失敗しました", "フェードアウト", "再生停止前に音量を下げます", "おやすみスケジュール", "スリープタイマーを自動で開始します", "開始時刻", "長さ", "繰り返し", "オートメーション", "Bluetooth 再接続時に再生を再開", "オーディオ機器の切断による一時停止のあとのみ", "ミュート時に一時停止", "メディア音量がゼロになったら再生を一時停止します", "お気に入りの曲を自動ダウンロード", "曲をお気に入りにするとダウンロードをキューに追加します", "回復不能な再生エラー後にスキップ", "通常の回復処理が失敗したあとのみ")
    "ko" -> LevyraAutomationCopy("Spotify에서 가져오기", "내보낸 Spotify CSV로 재생목록 만들기", "CSV 선택", "재생목록 이름", "가져오는 중…", "일치", "불일치", "가져오기 실패", "페이드 아웃", "재생이 멈추기 전에 볼륨을 낮춥니다", "취침 예약", "취침 타이머를 자동으로 시작합니다", "시작 시간", "길이", "반복", "자동화", "블루투스 재연결 시 재생 재개", "오디오 기기 연결이 끊겨 일시정지된 경우에만", "음소거 시 일시정지", "미디어 볼륨이 0이 되면 재생을 일시정지합니다", "좋아요 표시한 곡 자동 다운로드", "곡에 좋아요를 누르면 다운로드를 대기열에 추가합니다", "복구 불가능한 재생 오류 후 건너뛰기", "일반 복구 시도가 실패한 뒤에만")
    "hi" -> LevyraAutomationCopy("Spotify से आयात करें", "निर्यात की गई Spotify CSV से प्लेलिस्ट बनाएँ", "CSV चुनें", "प्लेलिस्ट का नाम", "आयात हो रहा है…", "मिले", "नहीं मिले", "आयात विफल", "फ़ेड आउट", "प्लेबैक रुकने से पहले वॉल्यूम कम करता है", "सोने का शेड्यूल", "स्लीप टाइमर अपने आप शुरू करता है", "शुरू होने का समय", "अवधि", "दोहराएँ", "स्वचालन", "ब्लूटूथ फिर से जुड़ने पर प्लेबैक जारी रखें", "केवल ऑडियो डिवाइस छूटने से हुए पॉज़ के बाद", "म्यूट होने पर रोकें", "मीडिया वॉल्यूम शून्य होने पर प्लेबैक रोकता है", "पसंद किए गए गाने अपने आप डाउनलोड करें", "गाना पसंद करने पर डाउनलोड कतार में डालता है", "अपूरणीय त्रुटि के बाद ट्रैक छोड़ें", "केवल सामान्य रिकवरी प्रयास विफल होने के बाद")
    "id" -> LevyraAutomationCopy("Impor dari Spotify", "Buat playlist dari CSV Spotify yang diekspor", "Pilih CSV", "Nama playlist", "Mengimpor…", "Cocok", "Tidak cocok", "Impor gagal", "Fade out", "Menurunkan volume sebelum pemutaran berhenti", "Jadwal tidur", "Memulai sleep timer secara otomatis", "Waktu mulai", "Durasi", "Ulangi", "Otomatisasi", "Lanjutkan pemutaran saat Bluetooth tersambung lagi", "Hanya setelah jeda karena perangkat audio terputus", "Jeda saat volume dibisukan", "Menjeda pemutaran saat volume media mencapai nol", "Unduh otomatis lagu yang disukai", "Menambahkan unduhan ke antrean saat kamu menyukai lagu", "Lewati lagu setelah galat yang tak dapat dipulihkan", "Hanya setelah upaya pemulihan normal gagal")
    "vi" -> LevyraAutomationCopy("Nhập từ Spotify", "Tạo danh sách phát từ tệp CSV xuất ra từ Spotify", "Chọn CSV", "Tên danh sách phát", "Đang nhập…", "Khớp", "Không khớp", "Nhập thất bại", "Nhỏ dần", "Giảm âm lượng trước khi dừng phát", "Lịch đi ngủ", "Tự động bắt đầu hẹn giờ ngủ", "Giờ bắt đầu", "Thời lượng", "Lặp lại", "Tự động hoá", "Tiếp tục phát khi Bluetooth kết nối lại", "Chỉ sau khi tạm dừng do mất thiết bị âm thanh", "Tạm dừng khi tắt tiếng", "Tạm dừng phát khi âm lượng phương tiện về không", "Tự động tải bài hát đã thích", "Thêm lượt tải vào hàng đợi khi bạn thích một bài hát", "Bỏ qua bài sau lỗi phát không thể khắc phục", "Chỉ sau khi các lần khôi phục thông thường thất bại")
    "th" -> LevyraAutomationCopy("นำเข้าจาก Spotify", "สร้างเพลย์ลิสต์จากไฟล์ CSV ที่ส่งออกจาก Spotify", "เลือก CSV", "ชื่อเพลย์ลิสต์", "กำลังนำเข้า…", "จับคู่ได้", "จับคู่ไม่ได้", "นำเข้าไม่สำเร็จ", "ค่อย ๆ เบาลง", "ลดระดับเสียงก่อนหยุดเล่น", "ตารางเข้านอน", "เริ่มตัวตั้งเวลานอนอัตโนมัติ", "เวลาเริ่ม", "ระยะเวลา", "ทำซ้ำ", "ระบบอัตโนมัติ", "เล่นต่อเมื่อเชื่อมต่อบลูทูธอีกครั้ง", "เฉพาะหลังจากหยุดชั่วคราวเพราะอุปกรณ์เสียงหลุด", "หยุดชั่วคราวเมื่อปิดเสียง", "หยุดเล่นเมื่อระดับเสียงสื่อเป็นศูนย์", "ดาวน์โหลดเพลงที่ถูกใจอัตโนมัติ", "เพิ่มการดาวน์โหลดเข้าคิวเมื่อคุณกดถูกใจเพลง", "ข้ามเพลงหลังเกิดข้อผิดพลาดที่กู้คืนไม่ได้", "เฉพาะหลังจากการกู้คืนตามปกติล้มเหลว")
    "fil" -> LevyraAutomationCopy("Mag-import mula sa Spotify", "Gumawa ng playlist mula sa na-export na Spotify CSV", "Pumili ng CSV", "Pangalan ng playlist", "Nag-i-import…", "Natugma", "Hindi natugma", "Nabigo ang pag-import", "Fade out", "Hinihina ang volume bago huminto ang pagpapatugtog", "Iskedyul ng tulog", "Awtomatikong sinisimulan ang sleep timer", "Oras ng simula", "Tagal", "Ulitin", "Mga automation", "Ipagpatuloy ang pagpapatugtog kapag nakabalik ang Bluetooth", "Pagkatapos lang ng pause dahil nawala ang audio device", "I-pause kapag naka-mute", "Ipinapause ang pagpapatugtog kapag zero na ang media volume", "Awtomatikong i-download ang mga gustong kanta", "Nagda-download kapag nag-like ka ng kanta", "Laktawan ang track pagkatapos ng hindi na maaayos na error", "Pagkatapos lang mabigo ang normal na pagbawi")
    "he" -> LevyraAutomationCopy("ייבוא מ-Spotify", "צור פלייליסט מקובץ CSV שיוצא מ-Spotify", "בחר CSV", "שם הפלייליסט", "מייבא…", "נמצאו", "לא נמצאו", "הייבוא נכשל", "עמעום", "מנמיך את עוצמת הקול לפני עצירת ההשמעה", "לוח זמנים לשינה", "מפעיל את טיימר השינה אוטומטית", "שעת התחלה", "משך", "חזרה", "אוטומציות", "חידוש השמעה בחיבור Bluetooth מחדש", "רק אחרי השהיה שנגרמה מאובדן התקן השמע", "השהיה כשעוצמת הקול מושתקת", "משהה את ההשמעה כשעוצמת המדיה מגיעה לאפס", "הורדה אוטומטית של שירים אהובים", "מוסיף הורדה לתור כשאתה מסמן שיר כאהוב", "דילוג על רצועה אחרי שגיאה בלתי הפיכה", "רק לאחר כישלון ניסיונות השחזור הרגילים")
    else -> LevyraAutomationCopy("Import from Spotify", "Create a playlist from an exported Spotify CSV", "Choose CSV", "Playlist name", "Importing…", "Matched", "Not matched", "Import failed", "Fade out", "Lower the volume before playback stops", "Bedtime schedule", "Start the sleep timer automatically", "Start time", "Duration", "Repeat", "Automation", "Resume playback on Bluetooth reconnect", "Only after a pause caused by losing the audio device", "Pause when volume is muted", "Pause playback when the media volume reaches zero", "Download liked songs automatically", "Queue a download when you like a song", "Skip track after unrecoverable playback error", "Only after the normal recovery attempts have failed")
}
