package com.luc4n3x.levyra.data

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test

class YoutubeMusicPlaylistPageParserTest {
    @Test
    fun readsRegularPlaylistShelf() {
        val root = initialPage("musicPlaylistShelfRenderer", "VIDEO_A", "TOKEN_A")

        assertEquals(listOf("VIDEO_A"), rendererVideoIds(root))
        assertEquals("TOKEN_A", YoutubeMusicPlaylistPageParser.continuation(root))
    }

    @Test
    fun readsAutoGeneratedMusicShelf() {
        val root = initialPage("musicShelfRenderer", "VIDEO_B", "TOKEN_B")

        assertEquals(listOf("VIDEO_B"), rendererVideoIds(root))
        assertEquals("TOKEN_B", YoutubeMusicPlaylistPageParser.continuation(root))
    }

    @Test
    fun readsBothContinuationShelfShapes() {
        val playlistContinuation = continuationPage(
            shelfKey = "musicPlaylistShelfContinuation",
            videoId = "VIDEO_C",
            token = "TOKEN_C"
        )
        val musicContinuation = continuationPage(
            shelfKey = "musicShelfContinuation",
            videoId = "VIDEO_D",
            token = "TOKEN_D"
        )

        assertEquals(listOf("VIDEO_C"), rendererVideoIds(playlistContinuation))
        assertEquals("TOKEN_C", YoutubeMusicPlaylistPageParser.continuation(playlistContinuation))
        assertEquals(listOf("VIDEO_D"), rendererVideoIds(musicContinuation))
        assertEquals("TOKEN_D", YoutubeMusicPlaylistPageParser.continuation(musicContinuation))
    }

    @Test
    fun readsActionBasedContinuationPage() {
        val root = JSONObject(
            """
            {
              "onResponseReceivedActions": [
                {
                  "appendContinuationItemsAction": {
                    "continuationItems": [
                      ${rendererItem("VIDEO_E")},
                      ${continuationItem("TOKEN_E")}
                    ]
                  }
                }
              ]
            }
            """.trimIndent()
        )

        assertEquals(listOf("VIDEO_E"), rendererVideoIds(root))
        assertEquals("TOKEN_E", YoutubeMusicPlaylistPageParser.continuation(root))
    }


    @Test
    fun readsReloadContinuationCommand() {
        val root = JSONObject(
            """
            {
              "onResponseReceivedEndpoints": [
                {
                  "reloadContinuationItemsCommand": {
                    "continuationItems": [
                      ${rendererItem("VIDEO_F")},
                      ${continuationItem("TOKEN_F")}
                    ]
                  }
                }
              ]
            }
            """.trimIndent()
        )

        assertEquals(listOf("VIDEO_F"), rendererVideoIds(root))
        assertEquals("TOKEN_F", YoutubeMusicPlaylistPageParser.continuation(root))
    }

    @Test
    fun playlistTrackDoesNotRequireSetVideoId() {
        val root = initialPage("musicShelfRenderer", "VIDEO_NO_SET", "")

        val tracks = YoutubeMusicRepository().parsePlaylistTracks(root, "PLAYLIST_ID")

        assertEquals(1, tracks.size)
        assertEquals("VIDEO_NO_SET", tracks.single().id)
        assertEquals("Example song", tracks.single().title)
    }

    @Test
    fun unavailableRendererStillCountsAsRawPageProgress() {
        val root = JSONObject(
            """
            {
              "continuationContents": {
                "musicPlaylistShelfContinuation": {
                  "contents": [
                    ${unavailableRendererItem()},
                    ${continuationItem("TOKEN_AFTER_UNAVAILABLE")}
                  ]
                }
              }
            }
            """.trimIndent()
        )

        val renderers = YoutubeMusicPlaylistPageParser.renderers(root)
        val tracks = YoutubeMusicRepository().parsePlaylistTracks(root, "PLAYLIST_ID")

        assertEquals(1, renderers.size)
        assertEquals(0, tracks.size)
        assertEquals("TOKEN_AFTER_UNAVAILABLE", YoutubeMusicPlaylistPageParser.continuation(root))
    }

    private fun rendererVideoIds(root: JSONObject): List<String> =
        YoutubeMusicPlaylistPageParser.renderers(root).map { renderer ->
            renderer.optJSONObject("playlistItemData")?.optString("videoId").orEmpty()
        }

    private fun initialPage(shelfKey: String, videoId: String, token: String): JSONObject = JSONObject(
        """
        {
          "contents": {
            "singleColumnBrowseResultsRenderer": {
              "tabs": [
                {
                  "tabRenderer": {
                    "content": {
                      "sectionListRenderer": {
                        "contents": [
                          {
                            "$shelfKey": {
                              "contents": [
                                ${rendererItem(videoId)}
                              ],
                              "continuations": [
                                {
                                  "nextContinuationData": {
                                    "continuation": "$token"
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
        """.trimIndent()
    )

    private fun continuationPage(shelfKey: String, videoId: String, token: String): JSONObject = JSONObject(
        """
        {
          "continuationContents": {
            "$shelfKey": {
              "contents": [
                ${rendererItem(videoId)},
                ${continuationItem(token)}
              ]
            }
          }
        }
        """.trimIndent()
    )

    private fun rendererItem(videoId: String): String =
        """
        {
          "musicResponsiveListItemRenderer": {
            "playlistItemData": {
              "videoId": "$videoId"
            },
            "flexColumns": [
              {
                "musicResponsiveListItemFlexColumnRenderer": {
                  "text": {
                    "runs": [
                      {"text": "Example song"}
                    ]
                  }
                }
              },
              {
                "musicResponsiveListItemFlexColumnRenderer": {
                  "text": {
                    "runs": [
                      {"text": "Example artist"},
                      {"text": " • "},
                      {"text": "Example album"},
                      {"text": " • "},
                      {"text": "3:20"}
                    ]
                  }
                }
              }
            ]
          }
        }
        """.trimIndent()

    private fun unavailableRendererItem(): String =
        """
        {
          "musicResponsiveListItemRenderer": {
            "playlistItemData": {
              "videoId": "UNAVAILABLE_VIDEO"
            },
            "flexColumns": []
          }
        }
        """.trimIndent()

    private fun continuationItem(token: String): String =
        """
        {
          "continuationItemRenderer": {
            "continuationEndpoint": {
              "continuationCommand": {
                "token": "$token"
              }
            }
          }
        }
        """.trimIndent()
}
